apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    prometheus: k8s
    role: alert-rules
  name: prometheus-nginx-rules
  namespace: monitoring
spec:
  groups:
    - name: err_rate
      rules:
      - record: job:nginx_request_duration_seconds_sum:err_rate_by_host
        expr: (sum(increase(nginx_request_duration_seconds_count{status!~"2..|403|304"}[10m])) by (host) / sum(increase(nginx_request_duration_seconds_count{}[10m])) by (host)) * 100
      - record: job:nginx_request_duration_seconds_sum:err_rate_by_host_path
        expr: (sum(increase(nginx_request_duration_seconds_count{status!~"2..|403|304"}[10m])) by (host,path) / sum(increase(nginx_request_duration_seconds_count{}[10m])) by (host,path)) * 100
      - record: job:nginx_request_duration_seconds_sum:err_rate_by_instance
        expr: (sum(increase(nginx_request_duration_seconds_count{status!~"2..|403|304"}[10m])) by (instance) / sum(increase(nginx_request_duration_seconds_count{}[10m])) by (instance)) * 100
      - record: job:nginx_request_duration_seconds_sum:err_rate_by_host_instance
        expr: (sum by(host,instance) (increase(nginx_request_duration_seconds_count{status!~"2..|403|304"}[10m])) / sum by(host,instance) (increase(nginx_request_duration_seconds_count[10m]))) * 100
  #    #总错误率
  #    - record: job:nginx_request_duration_seconds_sum:err_rate
  #      expr: (sum(increase(nginx_request_duration_seconds_count{status!~"2..|403|304"}[10m])) / sum(increase(nginx_request_duration_seconds_count{}[10m]))) * 100