apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    prometheus: k8s
    role: alert-rules
  name: prometheus-nginx-rules
  namespace: monitoring
spec:
  groups:
    - name: qps
      rules:
      # host
      - record: job:nginx_request_duration_seconds:qps_by_host_2XX
        expr: sum(rate(nginx_request_duration_seconds_count{status=~"2.."}[3m])) by (host)
      - record: job:nginx_request_duration_seconds:qps_by_host_4XX
        expr: sum(rate(nginx_request_duration_seconds_count{status=~"40[^3]{1}|4[^0]{1}."}[3m])) by (host)
      - record: job:nginx_request_duration_seconds:qps_by_host_403
        expr: sum(rate(nginx_request_duration_seconds_count{status=~"403"}[3m])) by (host)
      - record: job:nginx_request_duration_seconds:qps_by_host_5XX
        expr: sum(rate(nginx_request_duration_seconds_count{status=~"5.."}[3m])) by (host)
      # host, instance
      - record: job:nginx_request_duration_seconds:qps_by_instance_host_2XX
        expr: sum(rate(nginx_request_duration_seconds_count{status=~"2.."}[3m])) by (instance, host)
      - record: job:nginx_request_duration_seconds:qps_by_instance_host_4XX
        expr: sum(rate(nginx_request_duration_seconds_count{status=~"40[^3]{1}|4[^0]{1}."}[3m])) by (instance, host)
      - record: job:nginx_request_duration_seconds:qps_by_instance_host_5XX
        expr: sum(rate(nginx_request_duration_seconds_count{status=~"5.."}[3m])) by (instance, host)
      # host, path
      - record: job:nginx_request_duration_seconds:qps_by_host_path_2XX
        expr: sum(rate(nginx_request_duration_seconds_count{status=~"2.."}[3m])) by (host, path)
      - record: job:nginx_request_duration_seconds:qps_by_host_path_3XX
        expr: sum(rate(nginx_request_duration_seconds_count{status=~"3.."}[3m])) by (host, path)
      - record: job:nginx_request_duration_seconds:qps_by_host_path_4XX
        expr: sum(rate(nginx_request_duration_seconds_count{status=~"40[^3]{1}|4[^0]{1}."}[3m])) by (host, path)
      - record: job:nginx_request_duration_seconds:qps_by_host_path_5XX
        expr: sum(rate(nginx_request_duration_seconds_count{status=~"5.."}[3m])) by (host, path)
      # host, path, fullurl
      - record: job:nginx_request_duration_seconds:qps_by_host_path_fullurl_2XX
        expr: sum(rate(nginx_request_duration_seconds_count{status=~"2.."}[3m])) by (host, path, fullurl)
      # host, path, instance
      - record: job:nginx_request_duration_seconds:qps_by_instance_host_path_2XX
        expr: sum(rate(nginx_request_duration_seconds_count{status=~"2.."}[3m])) by (instance, host, path)
      - record: job:nginx_request_duration_seconds:qps_by_instance_host_path_4XX
        expr: sum(rate(nginx_request_duration_seconds_count{status=~"40[^3]{1}|4[^0]{1}."}[3m])) by (instance, host, path)
      - record: job:nginx_request_duration_seconds:qps_by_instance_host_path_5XX
        expr: sum(rate(nginx_request_duration_seconds_count{status=~"5.."}[3m])) by (instance, host, path)
      - record: job:nginx_request_duration_seconds:qps_by_instance_host_path_403
        expr: sum(rate(nginx_request_duration_seconds_count{status=~"403"}[3m])) by (instance, host, path)
      # host, path, fullurl, instance
      #- record: job:nginx_request_duration_seconds:qps_by_instance_host_path_fullurl_2XX
      #  expr: sum(rate(nginx_request_duration_seconds_count{status=~"2.."}[3m])) by (instance, host, path, fullurl)
  #    - record: job:nginx_request_duration_seconds:qps_by_instance_host_status_method_3XX
  #      expr: sum(rate(nginx_request_duration_seconds_count{status=~"3.."}[3m])) by (instance, host)
  #    - record: job:nginx_request_duration_seconds:qps_by_instance_host_status_method_403
  #      expr: sum(rate(nginx_request_duration_seconds_count{status=~"403"}[3m])) by (instance, host)
  #    - record: job:nginx_request_duration_seconds:qps_by_path_fullurl_2XX
  #      expr: sum(rate(nginx_request_duration_seconds_count{status=~"2.."}[3m])) by (path, fullurl)